apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-authorizer
  description: Payment Authorizer
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
annotations:
  backstage.io/techdocs-ref: dir:.

